DROP TABLE MEMBER;
CREATE TABLE MEMBER
(
	NUM NUMBER(5),
	ID VARCHAR2(20),
	NAME VARCHAR2(30),
	EMAIL VARCHAR2(30),
	PHONE VARCHAR2(20),
	ADDR VARCHAR2(50),
	HAGNYENO NUMBER(2),
	DEL_YN VARCHAR(5),
	AUTH NUMBER(3),
	USDATE DATE,
	CONSTRAINT MEMBER_NUM_PK PRIMARY KEY(NUM)
);

DROP SEQUENCE MEMBER_NUM_SEQ;
CREATE SEQUENCE MEMBER_NUM_SEQ;

DROP TABLE PASS;
CREATE TABLE PASS
(
	NUM NUMBER(5),
	ID VARCHAR2(20),
	PASS VARCHAR2(20),
	DEL_YN VARCHAR(5),
	CONSTRAINT PASS_NUM_PK PRIMARY KEY(NUM),
	CONSTRAINT PASS_NUM_FK FOREIGN KEY(NUM) REFERENCES MEMBER(NUM)
);

DROP TABLE DEPARTMENT;
CREATE TABLE DEPARTMENT
(
	DENUM NUMBER(5),
	NAME VARCHAR2(20),
	DEL_YN VARCHAR(5),
	CONSTRAINT DEPARTMENT_DENUM_PK PRIMARY KEY(DENUM)
);

CREATE SEQUENCE DEPARTMENT_DENUM_SEQ;

DROP TABLE DRM_MEMBER;
CREATE TABLE DRM_MEMBER
(
	DENUM NUMBER(5),
	NUM NUMBER(5),
	DIVISION NUMBER(5),
	DEL_YN VARCHAR(5),
	CONSTRAINT DPM_MEMBER_PK PRIMARY KEY(DENUM, NUM),
	CONSTRAINT DPM_MEMBER_NUM_FK FOREIGN KEY(NUM) REFERENCES MEMBER(NUM),
    CONSTRAINT DPM_MEMBER_DENUM_FK FOREIGN KEY(DENUM) REFERENCES DEPARTMENT(DENUM)
);

CREATE SEQUENCE LECTURE_LENUM_SEQ;

DROP TABLE LECTURE;
CREATE TABLE LECTURE
(
	LENUM NUMBER(5),
	NUM NUMBER(5),
	NAME VARCHAR2(30),
	DEL_YN VARCHAR(5),
	CONSTRAINT LECTURE_LENUM_PK PRIMARY KEY(LENUM),
	CONSTRAINT LECTURE_NUM_FK FOREIGN KEY(NUM) REFERENCES MEMBER(NUM)
);

DROP TABLE LEC_MEMBER;
CREATE TABLE LEC_MEMBER
(
	LENUM NUMBER(5),
	NUM NUMBER(5),
	LEDATE DATE,
	DEL_YN VARCHAR(5),
	CONSTRAINT LEC_MEMBER_PK PRIMARY KEY(LENUM, NUM),
	CONSTRAINT LEC_MEMBER_LENUM_FK FOREIGN KEY(LENUM) REFERENCES LECTURE(LENUM),
	CONSTRAINT LEC_MEMBER_NUM_FK FOREIGN KEY(NUM) REFERENCES MEMBER(NUM)
);

DROP TABLE GRADE;
CREATE TABLE GRADE
(
	LENUM NUMBER(5),
	NUM NUMBER(5),
	SCORE NUMBER(4),
	RANK VARCHAR2(20),
	DEL_YN VARCHAR(5),
	GRDATE DATE,
	CONSTRAINT GRADE_PK PRIMARY KEY(LENUM, NUM),
	CONSTRAINT GRADE_LENUM_FK FOREIGN KEY(LENUM) REFERENCES LECTURE(LENUM),
	CONSTRAINT GRADE_NUM_FK FOREIGN KEY(NUM) REFERENCES MEMBER(NUM)
);
